# Nombre y clave del proyecto en SonarCloud
sonar.projectKey=Jonathan03R_Proyecto_calidad_sofware
sonar.organization=jonathan03r

# Ruta principal (ajústalo si tu .sln está en otra carpeta)
sonar.sources=.

# Ignorar librerías JS y CSS
sonar.exclusions=**/Scripts/**, **/Content/**, **/*.min.js**, **/*.min.css**, **/*.map**, **/node_modules/**, **/wwwroot/lib/**

# Ignorar archivos generados de ASP.NET Framework
sonar.exclusions=**/obj/**, **/bin/**


sonar.exclusions=capa_presentacion/Scripts/**,capa_presentacion/Content/**,**/*.min.js,**/*.js.map


sonar.language=cs
sonar.cs.file.suffixes=.cs
