# Proyecto
sonar.projectKey=Jonathan03R_Proyecto_calidad_sofware
sonar.organization=jonathan03r
sonar.sources=.

# Ignorar librerías JS/CSS y carpetas ASP.NET
sonar.exclusions=\
**/Scripts/**,\
**/Content/**,\
**/*.min.js,\
**/*.min.css,\
**/*.js.map,\
**/*.map,\
**/node_modules/**,\
**/wwwroot/lib/**,\
**/obj/**,\
**/bin/**,\
capa_presentacion/Scripts/**,\
capa_presentacion/Content/**

# C#
sonar.language=cs
sonar.cs.file.suffixes=.cs

# Ignorar duplicación en DTOs (opcional)
sonar.cpd.exclusions=**/*DTO.cs
